/*
* generated by Xtext
*/

package org.xtext.example.mydsl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class MyDslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class IntentModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "IntentModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cIntentModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cNameModelKeyword_1_0 = (Keyword)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftSquareBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cIntentsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cIntentsIntentParserRuleCall_4_1_0 = (RuleCall)cIntentsAssignment_4_1.eContents().get(0);
		private final Group cGroup_4_2 = (Group)cGroup_4.eContents().get(2);
		private final Keyword cCommaKeyword_4_2_0 = (Keyword)cGroup_4_2.eContents().get(0);
		private final Assignment cIntentsAssignment_4_2_1 = (Assignment)cGroup_4_2.eContents().get(1);
		private final RuleCall cIntentsIntentParserRuleCall_4_2_1_0 = (RuleCall)cIntentsAssignment_4_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_3 = (Keyword)cGroup_4.eContents().get(3);
		private final Keyword cRightSquareBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//IntentModel:
		//	{IntentModel} name="Model" "=" "[" ("{" intents+=Intent ("," intents+=Intent)* "}")? "]";
		public ParserRule getRule() { return rule; }

		//{IntentModel} name="Model" "=" "[" ("{" intents+=Intent ("," intents+=Intent)* "}")? "]"
		public Group getGroup() { return cGroup; }

		//{IntentModel}
		public Action getIntentModelAction_0() { return cIntentModelAction_0; }

		//name="Model"
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//"Model"
		public Keyword getNameModelKeyword_1_0() { return cNameModelKeyword_1_0; }

		//"="
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }

		//"["
		public Keyword getLeftSquareBracketKeyword_3() { return cLeftSquareBracketKeyword_3; }

		//("{" intents+=Intent ("," intents+=Intent)* "}")?
		public Group getGroup_4() { return cGroup_4; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_0() { return cLeftCurlyBracketKeyword_4_0; }

		//intents+=Intent
		public Assignment getIntentsAssignment_4_1() { return cIntentsAssignment_4_1; }

		//Intent
		public RuleCall getIntentsIntentParserRuleCall_4_1_0() { return cIntentsIntentParserRuleCall_4_1_0; }

		//("," intents+=Intent)*
		public Group getGroup_4_2() { return cGroup_4_2; }

		//","
		public Keyword getCommaKeyword_4_2_0() { return cCommaKeyword_4_2_0; }

		//intents+=Intent
		public Assignment getIntentsAssignment_4_2_1() { return cIntentsAssignment_4_2_1; }

		//Intent
		public RuleCall getIntentsIntentParserRuleCall_4_2_1_0() { return cIntentsIntentParserRuleCall_4_2_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_3() { return cRightCurlyBracketKeyword_4_3; }

		//"]"
		public Keyword getRightSquareBracketKeyword_5() { return cRightSquareBracketKeyword_5; }
	}

	public class IntentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Intent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTypeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final RuleCall cExplicitIntentParserRuleCall_2_0 = (RuleCall)cAlternatives_2.eContents().get(0);
		private final RuleCall cImplicitIntentParserRuleCall_2_1 = (RuleCall)cAlternatives_2.eContents().get(1);
		private final RuleCall cBroadcastIntentParserRuleCall_2_2 = (RuleCall)cAlternatives_2.eContents().get(2);
		private final RuleCall cServiceIntentParserRuleCall_2_3 = (RuleCall)cAlternatives_2.eContents().get(3);
		private final Keyword cCommaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Group cGroup_4_0 = (Group)cGroup_4.eContents().get(0);
		private final Keyword cNameKeyword_4_0_0 = (Keyword)cGroup_4_0.eContents().get(0);
		private final Keyword cColonKeyword_4_0_1 = (Keyword)cGroup_4_0.eContents().get(1);
		private final Assignment cNameAssignment_4_0_2 = (Assignment)cGroup_4_0.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_4_0_2_0 = (RuleCall)cNameAssignment_4_0_2.eContents().get(0);
		private final Keyword cCommaKeyword_4_0_3 = (Keyword)cGroup_4_0.eContents().get(3);
		private final Group cGroup_4_1 = (Group)cGroup_4.eContents().get(1);
		private final Keyword cActionKeyword_4_1_0 = (Keyword)cGroup_4_1.eContents().get(0);
		private final Keyword cColonKeyword_4_1_1 = (Keyword)cGroup_4_1.eContents().get(1);
		private final Assignment cActionAssignment_4_1_2 = (Assignment)cGroup_4_1.eContents().get(2);
		private final RuleCall cActionEStringParserRuleCall_4_1_2_0 = (RuleCall)cActionAssignment_4_1_2.eContents().get(0);
		private final Keyword cCommaKeyword_4_1_3 = (Keyword)cGroup_4_1.eContents().get(3);
		private final Group cGroup_4_2 = (Group)cGroup_4.eContents().get(2);
		private final Keyword cCategoryKeyword_4_2_0 = (Keyword)cGroup_4_2.eContents().get(0);
		private final Keyword cColonKeyword_4_2_1 = (Keyword)cGroup_4_2.eContents().get(1);
		private final Assignment cCategoryAssignment_4_2_2 = (Assignment)cGroup_4_2.eContents().get(2);
		private final RuleCall cCategoryEStringParserRuleCall_4_2_2_0 = (RuleCall)cCategoryAssignment_4_2_2.eContents().get(0);
		private final Keyword cCommaKeyword_4_2_3 = (Keyword)cGroup_4_2.eContents().get(3);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cDataURIKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Keyword cColonKeyword_4_3_1 = (Keyword)cGroup_4_3.eContents().get(1);
		private final Assignment cDataURIAssignment_4_3_2 = (Assignment)cGroup_4_3.eContents().get(2);
		private final RuleCall cDataURIEStringParserRuleCall_4_3_2_0 = (RuleCall)cDataURIAssignment_4_3_2.eContents().get(0);
		private final Keyword cCommaKeyword_4_3_3 = (Keyword)cGroup_4_3.eContents().get(3);
		private final Group cGroup_4_4 = (Group)cGroup_4.eContents().get(4);
		private final Keyword cDataExtraKeyword_4_4_0 = (Keyword)cGroup_4_4.eContents().get(0);
		private final Keyword cColonKeyword_4_4_1 = (Keyword)cGroup_4_4.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_4_4_2 = (Keyword)cGroup_4_4.eContents().get(2);
		private final Assignment cExtraDataAssignment_4_4_3 = (Assignment)cGroup_4_4.eContents().get(3);
		private final RuleCall cExtraDataExtraDataParserRuleCall_4_4_3_0 = (RuleCall)cExtraDataAssignment_4_4_3.eContents().get(0);
		private final Group cGroup_4_4_4 = (Group)cGroup_4_4.eContents().get(4);
		private final Keyword cCommaKeyword_4_4_4_0 = (Keyword)cGroup_4_4_4.eContents().get(0);
		private final Assignment cExtraDataAssignment_4_4_4_1 = (Assignment)cGroup_4_4_4.eContents().get(1);
		private final RuleCall cExtraDataExtraDataParserRuleCall_4_4_4_1_0 = (RuleCall)cExtraDataAssignment_4_4_4_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_4_4_5 = (Keyword)cGroup_4_4.eContents().get(5);
		private final Keyword cCommaKeyword_4_4_6 = (Keyword)cGroup_4_4.eContents().get(6);
		private final Group cGroup_4_5 = (Group)cGroup_4.eContents().get(5);
		private final Keyword cReturnDataKeyword_4_5_0 = (Keyword)cGroup_4_5.eContents().get(0);
		private final Keyword cColonKeyword_4_5_1 = (Keyword)cGroup_4_5.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_4_5_2 = (Keyword)cGroup_4_5.eContents().get(2);
		private final Assignment cReturnDataAssignment_4_5_3 = (Assignment)cGroup_4_5.eContents().get(3);
		private final RuleCall cReturnDataExtraDataParserRuleCall_4_5_3_0 = (RuleCall)cReturnDataAssignment_4_5_3.eContents().get(0);
		private final Group cGroup_4_5_4 = (Group)cGroup_4_5.eContents().get(4);
		private final Keyword cCommaKeyword_4_5_4_0 = (Keyword)cGroup_4_5_4.eContents().get(0);
		private final Assignment cReturnDataAssignment_4_5_4_1 = (Assignment)cGroup_4_5_4.eContents().get(1);
		private final RuleCall cReturnDataExtraDataParserRuleCall_4_5_4_1_0 = (RuleCall)cReturnDataAssignment_4_5_4_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_4_5_5 = (Keyword)cGroup_4_5.eContents().get(5);
		private final Keyword cCommaKeyword_4_5_6 = (Keyword)cGroup_4_5.eContents().get(6);
		
		//Intent:
		//	"Type" ":" (ExplicitIntent | ImplicitIntent | BroadcastIntent | ServiceIntent) "," (("Name" ":" name=EString ",")
		//	("Action" ":" action=EString ",") ("Category" ":" category=EString ",") ("DataURI" ":" dataURI=EString ",")
		//	("DataExtra" ":" "[" extraData+=ExtraData ("," extraData+=ExtraData)* "]" ",")? ("ReturnData" ":" "["
		//	returnData+=ExtraData ("," returnData+=ExtraData)* "]" ",")?);
		public ParserRule getRule() { return rule; }

		//"Type" ":" (ExplicitIntent | ImplicitIntent | BroadcastIntent | ServiceIntent) "," (("Name" ":" name=EString ",")
		//("Action" ":" action=EString ",") ("Category" ":" category=EString ",") ("DataURI" ":" dataURI=EString ",")
		//("DataExtra" ":" "[" extraData+=ExtraData ("," extraData+=ExtraData)* "]" ",")? ("ReturnData" ":" "["
		//returnData+=ExtraData ("," returnData+=ExtraData)* "]" ",")?)
		public Group getGroup() { return cGroup; }

		//"Type"
		public Keyword getTypeKeyword_0() { return cTypeKeyword_0; }

		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }

		//ExplicitIntent | ImplicitIntent | BroadcastIntent | ServiceIntent
		public Alternatives getAlternatives_2() { return cAlternatives_2; }

		//ExplicitIntent
		public RuleCall getExplicitIntentParserRuleCall_2_0() { return cExplicitIntentParserRuleCall_2_0; }

		//ImplicitIntent
		public RuleCall getImplicitIntentParserRuleCall_2_1() { return cImplicitIntentParserRuleCall_2_1; }

		//BroadcastIntent
		public RuleCall getBroadcastIntentParserRuleCall_2_2() { return cBroadcastIntentParserRuleCall_2_2; }

		//ServiceIntent
		public RuleCall getServiceIntentParserRuleCall_2_3() { return cServiceIntentParserRuleCall_2_3; }

		//","
		public Keyword getCommaKeyword_3() { return cCommaKeyword_3; }

		//("Name" ":" name=EString ",") ("Action" ":" action=EString ",") ("Category" ":" category=EString ",") ("DataURI" ":"
		//dataURI=EString ",") ("DataExtra" ":" "[" extraData+=ExtraData ("," extraData+=ExtraData)* "]" ",")? ("ReturnData" ":"
		//"[" returnData+=ExtraData ("," returnData+=ExtraData)* "]" ",")?
		public Group getGroup_4() { return cGroup_4; }

		//"Name" ":" name=EString ","
		public Group getGroup_4_0() { return cGroup_4_0; }

		//"Name"
		public Keyword getNameKeyword_4_0_0() { return cNameKeyword_4_0_0; }

		//":"
		public Keyword getColonKeyword_4_0_1() { return cColonKeyword_4_0_1; }

		//name=EString
		public Assignment getNameAssignment_4_0_2() { return cNameAssignment_4_0_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_4_0_2_0() { return cNameEStringParserRuleCall_4_0_2_0; }

		//","
		public Keyword getCommaKeyword_4_0_3() { return cCommaKeyword_4_0_3; }

		//"Action" ":" action=EString ","
		public Group getGroup_4_1() { return cGroup_4_1; }

		//"Action"
		public Keyword getActionKeyword_4_1_0() { return cActionKeyword_4_1_0; }

		//":"
		public Keyword getColonKeyword_4_1_1() { return cColonKeyword_4_1_1; }

		//action=EString
		public Assignment getActionAssignment_4_1_2() { return cActionAssignment_4_1_2; }

		//EString
		public RuleCall getActionEStringParserRuleCall_4_1_2_0() { return cActionEStringParserRuleCall_4_1_2_0; }

		//","
		public Keyword getCommaKeyword_4_1_3() { return cCommaKeyword_4_1_3; }

		//"Category" ":" category=EString ","
		public Group getGroup_4_2() { return cGroup_4_2; }

		//"Category"
		public Keyword getCategoryKeyword_4_2_0() { return cCategoryKeyword_4_2_0; }

		//":"
		public Keyword getColonKeyword_4_2_1() { return cColonKeyword_4_2_1; }

		//category=EString
		public Assignment getCategoryAssignment_4_2_2() { return cCategoryAssignment_4_2_2; }

		//EString
		public RuleCall getCategoryEStringParserRuleCall_4_2_2_0() { return cCategoryEStringParserRuleCall_4_2_2_0; }

		//","
		public Keyword getCommaKeyword_4_2_3() { return cCommaKeyword_4_2_3; }

		//"DataURI" ":" dataURI=EString ","
		public Group getGroup_4_3() { return cGroup_4_3; }

		//"DataURI"
		public Keyword getDataURIKeyword_4_3_0() { return cDataURIKeyword_4_3_0; }

		//":"
		public Keyword getColonKeyword_4_3_1() { return cColonKeyword_4_3_1; }

		//dataURI=EString
		public Assignment getDataURIAssignment_4_3_2() { return cDataURIAssignment_4_3_2; }

		//EString
		public RuleCall getDataURIEStringParserRuleCall_4_3_2_0() { return cDataURIEStringParserRuleCall_4_3_2_0; }

		//","
		public Keyword getCommaKeyword_4_3_3() { return cCommaKeyword_4_3_3; }

		//("DataExtra" ":" "[" extraData+=ExtraData ("," extraData+=ExtraData)* "]" ",")?
		public Group getGroup_4_4() { return cGroup_4_4; }

		//"DataExtra"
		public Keyword getDataExtraKeyword_4_4_0() { return cDataExtraKeyword_4_4_0; }

		//":"
		public Keyword getColonKeyword_4_4_1() { return cColonKeyword_4_4_1; }

		//"["
		public Keyword getLeftSquareBracketKeyword_4_4_2() { return cLeftSquareBracketKeyword_4_4_2; }

		//extraData+=ExtraData
		public Assignment getExtraDataAssignment_4_4_3() { return cExtraDataAssignment_4_4_3; }

		//ExtraData
		public RuleCall getExtraDataExtraDataParserRuleCall_4_4_3_0() { return cExtraDataExtraDataParserRuleCall_4_4_3_0; }

		//("," extraData+=ExtraData)*
		public Group getGroup_4_4_4() { return cGroup_4_4_4; }

		//","
		public Keyword getCommaKeyword_4_4_4_0() { return cCommaKeyword_4_4_4_0; }

		//extraData+=ExtraData
		public Assignment getExtraDataAssignment_4_4_4_1() { return cExtraDataAssignment_4_4_4_1; }

		//ExtraData
		public RuleCall getExtraDataExtraDataParserRuleCall_4_4_4_1_0() { return cExtraDataExtraDataParserRuleCall_4_4_4_1_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_4_4_5() { return cRightSquareBracketKeyword_4_4_5; }

		//","
		public Keyword getCommaKeyword_4_4_6() { return cCommaKeyword_4_4_6; }

		//("ReturnData" ":" "[" returnData+=ExtraData ("," returnData+=ExtraData)* "]" ",")?
		public Group getGroup_4_5() { return cGroup_4_5; }

		//"ReturnData"
		public Keyword getReturnDataKeyword_4_5_0() { return cReturnDataKeyword_4_5_0; }

		//":"
		public Keyword getColonKeyword_4_5_1() { return cColonKeyword_4_5_1; }

		//"["
		public Keyword getLeftSquareBracketKeyword_4_5_2() { return cLeftSquareBracketKeyword_4_5_2; }

		//returnData+=ExtraData
		public Assignment getReturnDataAssignment_4_5_3() { return cReturnDataAssignment_4_5_3; }

		//ExtraData
		public RuleCall getReturnDataExtraDataParserRuleCall_4_5_3_0() { return cReturnDataExtraDataParserRuleCall_4_5_3_0; }

		//("," returnData+=ExtraData)*
		public Group getGroup_4_5_4() { return cGroup_4_5_4; }

		//","
		public Keyword getCommaKeyword_4_5_4_0() { return cCommaKeyword_4_5_4_0; }

		//returnData+=ExtraData
		public Assignment getReturnDataAssignment_4_5_4_1() { return cReturnDataAssignment_4_5_4_1; }

		//ExtraData
		public RuleCall getReturnDataExtraDataParserRuleCall_4_5_4_1_0() { return cReturnDataExtraDataParserRuleCall_4_5_4_1_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_4_5_5() { return cRightSquareBracketKeyword_4_5_5; }

		//","
		public Keyword getCommaKeyword_4_5_6() { return cCommaKeyword_4_5_6; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class ExtraDataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ExtraData");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cExtraDataAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cNameKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cColonKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cNameAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_2_0 = (RuleCall)cNameAssignment_2_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTypeKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cColonKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cTypeAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cTypeEStringParserRuleCall_3_2_0 = (RuleCall)cTypeAssignment_3_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		////Bundle returns Bundle:
		////	'Bundle' / * TODO: implement this rule and an appropriate IValueConverter * /;
		//ExtraData:
		//	{ExtraData} "{" ("Name" ":" name=EString) ("Type" ":" type=EString) "}";
		public ParserRule getRule() { return rule; }

		//{ExtraData} "{" ("Name" ":" name=EString) ("Type" ":" type=EString) "}"
		public Group getGroup() { return cGroup; }

		//{ExtraData}
		public Action getExtraDataAction_0() { return cExtraDataAction_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"Name" ":" name=EString
		public Group getGroup_2() { return cGroup_2; }

		//"Name"
		public Keyword getNameKeyword_2_0() { return cNameKeyword_2_0; }

		//":"
		public Keyword getColonKeyword_2_1() { return cColonKeyword_2_1; }

		//name=EString
		public Assignment getNameAssignment_2_2() { return cNameAssignment_2_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_2_0() { return cNameEStringParserRuleCall_2_2_0; }

		//"Type" ":" type=EString
		public Group getGroup_3() { return cGroup_3; }

		//"Type"
		public Keyword getTypeKeyword_3_0() { return cTypeKeyword_3_0; }

		//":"
		public Keyword getColonKeyword_3_1() { return cColonKeyword_3_1; }

		//type=EString
		public Assignment getTypeAssignment_3_2() { return cTypeAssignment_3_2; }

		//EString
		public RuleCall getTypeEStringParserRuleCall_3_2_0() { return cTypeEStringParserRuleCall_3_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class ExplicitIntentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ExplicitIntent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cExplicitIntentAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cExplicitIntentKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//ExplicitIntent:
		//	{ExplicitIntent} "\'ExplicitIntent\'";
		public ParserRule getRule() { return rule; }

		//{ExplicitIntent} "\'ExplicitIntent\'"
		public Group getGroup() { return cGroup; }

		//{ExplicitIntent}
		public Action getExplicitIntentAction_0() { return cExplicitIntentAction_0; }

		//"\'ExplicitIntent\'"
		public Keyword getExplicitIntentKeyword_1() { return cExplicitIntentKeyword_1; }
	}

	public class ImplicitIntentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ImplicitIntent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cImplicitIntentAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cImplicitIntentKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//ImplicitIntent:
		//	{ImplicitIntent} "\'ImplicitIntent\'";
		public ParserRule getRule() { return rule; }

		//{ImplicitIntent} "\'ImplicitIntent\'"
		public Group getGroup() { return cGroup; }

		//{ImplicitIntent}
		public Action getImplicitIntentAction_0() { return cImplicitIntentAction_0; }

		//"\'ImplicitIntent\'"
		public Keyword getImplicitIntentKeyword_1() { return cImplicitIntentKeyword_1; }
	}

	public class BroadcastIntentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BroadcastIntent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBroadCastIntentAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBroadcastIntentKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//BroadcastIntent returns BroadCastIntent:
		//	{BroadCastIntent} "\'BroadcastIntent\'";
		public ParserRule getRule() { return rule; }

		//{BroadCastIntent} "\'BroadcastIntent\'"
		public Group getGroup() { return cGroup; }

		//{BroadCastIntent}
		public Action getBroadCastIntentAction_0() { return cBroadCastIntentAction_0; }

		//"\'BroadcastIntent\'"
		public Keyword getBroadcastIntentKeyword_1() { return cBroadcastIntentKeyword_1; }
	}

	public class ServiceIntentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ServiceIntent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cServiceIntentAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cServiceIntentKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//ServiceIntent:
		//	{ServiceIntent} "\'ServiceIntent\'";
		public ParserRule getRule() { return rule; }

		//{ServiceIntent} "\'ServiceIntent\'"
		public Group getGroup() { return cGroup; }

		//{ServiceIntent}
		public Action getServiceIntentAction_0() { return cServiceIntentAction_0; }

		//"\'ServiceIntent\'"
		public Keyword getServiceIntentKeyword_1() { return cServiceIntentKeyword_1; }
	}
	
	
	private IntentModelElements pIntentModel;
	private IntentElements pIntent;
	private EStringElements pEString;
	private ExtraDataElements pExtraData;
	private ExplicitIntentElements pExplicitIntent;
	private ImplicitIntentElements pImplicitIntent;
	private BroadcastIntentElements pBroadcastIntent;
	private ServiceIntentElements pServiceIntent;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//IntentModel:
	//	{IntentModel} name="Model" "=" "[" ("{" intents+=Intent ("," intents+=Intent)* "}")? "]";
	public IntentModelElements getIntentModelAccess() {
		return (pIntentModel != null) ? pIntentModel : (pIntentModel = new IntentModelElements());
	}
	
	public ParserRule getIntentModelRule() {
		return getIntentModelAccess().getRule();
	}

	//Intent:
	//	"Type" ":" (ExplicitIntent | ImplicitIntent | BroadcastIntent | ServiceIntent) "," (("Name" ":" name=EString ",")
	//	("Action" ":" action=EString ",") ("Category" ":" category=EString ",") ("DataURI" ":" dataURI=EString ",")
	//	("DataExtra" ":" "[" extraData+=ExtraData ("," extraData+=ExtraData)* "]" ",")? ("ReturnData" ":" "["
	//	returnData+=ExtraData ("," returnData+=ExtraData)* "]" ",")?);
	public IntentElements getIntentAccess() {
		return (pIntent != null) ? pIntent : (pIntent = new IntentElements());
	}
	
	public ParserRule getIntentRule() {
		return getIntentAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return (pEString != null) ? pEString : (pEString = new EStringElements());
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	////Bundle returns Bundle:
	////	'Bundle' / * TODO: implement this rule and an appropriate IValueConverter * /;
	//ExtraData:
	//	{ExtraData} "{" ("Name" ":" name=EString) ("Type" ":" type=EString) "}";
	public ExtraDataElements getExtraDataAccess() {
		return (pExtraData != null) ? pExtraData : (pExtraData = new ExtraDataElements());
	}
	
	public ParserRule getExtraDataRule() {
		return getExtraDataAccess().getRule();
	}

	//ExplicitIntent:
	//	{ExplicitIntent} "\'ExplicitIntent\'";
	public ExplicitIntentElements getExplicitIntentAccess() {
		return (pExplicitIntent != null) ? pExplicitIntent : (pExplicitIntent = new ExplicitIntentElements());
	}
	
	public ParserRule getExplicitIntentRule() {
		return getExplicitIntentAccess().getRule();
	}

	//ImplicitIntent:
	//	{ImplicitIntent} "\'ImplicitIntent\'";
	public ImplicitIntentElements getImplicitIntentAccess() {
		return (pImplicitIntent != null) ? pImplicitIntent : (pImplicitIntent = new ImplicitIntentElements());
	}
	
	public ParserRule getImplicitIntentRule() {
		return getImplicitIntentAccess().getRule();
	}

	//BroadcastIntent returns BroadCastIntent:
	//	{BroadCastIntent} "\'BroadcastIntent\'";
	public BroadcastIntentElements getBroadcastIntentAccess() {
		return (pBroadcastIntent != null) ? pBroadcastIntent : (pBroadcastIntent = new BroadcastIntentElements());
	}
	
	public ParserRule getBroadcastIntentRule() {
		return getBroadcastIntentAccess().getRule();
	}

	//ServiceIntent:
	//	{ServiceIntent} "\'ServiceIntent\'";
	public ServiceIntentElements getServiceIntentAccess() {
		return (pServiceIntent != null) ? pServiceIntent : (pServiceIntent = new ServiceIntentElements());
	}
	
	public ParserRule getServiceIntentRule() {
		return getServiceIntentAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
