/**
 */
package IntentDSL.provider;

import IntentDSL.util.IntentDSLAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class IntentDSLItemProviderAdapterFactory extends IntentDSLAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public IntentDSLItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link IntentDSL.IntentModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IntentModelItemProvider intentModelItemProvider;

	/**
	 * This creates an adapter for a {@link IntentDSL.IntentModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIntentModelAdapter() {
		if (intentModelItemProvider == null) {
			intentModelItemProvider = new IntentModelItemProvider(this);
		}

		return intentModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IntentDSL.ExtraData} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtraDataItemProvider extraDataItemProvider;

	/**
	 * This creates an adapter for a {@link IntentDSL.ExtraData}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtraDataAdapter() {
		if (extraDataItemProvider == null) {
			extraDataItemProvider = new ExtraDataItemProvider(this);
		}

		return extraDataItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IntentDSL.ImplicitIntent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImplicitIntentItemProvider implicitIntentItemProvider;

	/**
	 * This creates an adapter for a {@link IntentDSL.ImplicitIntent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImplicitIntentAdapter() {
		if (implicitIntentItemProvider == null) {
			implicitIntentItemProvider = new ImplicitIntentItemProvider(this);
		}

		return implicitIntentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IntentDSL.BroadCastIntent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BroadCastIntentItemProvider broadCastIntentItemProvider;

	/**
	 * This creates an adapter for a {@link IntentDSL.BroadCastIntent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBroadCastIntentAdapter() {
		if (broadCastIntentItemProvider == null) {
			broadCastIntentItemProvider = new BroadCastIntentItemProvider(this);
		}

		return broadCastIntentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IntentDSL.ExplicitIntent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExplicitIntentItemProvider explicitIntentItemProvider;

	/**
	 * This creates an adapter for a {@link IntentDSL.ExplicitIntent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExplicitIntentAdapter() {
		if (explicitIntentItemProvider == null) {
			explicitIntentItemProvider = new ExplicitIntentItemProvider(this);
		}

		return explicitIntentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IntentDSL.ServiceIntent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceIntentItemProvider serviceIntentItemProvider;

	/**
	 * This creates an adapter for a {@link IntentDSL.ServiceIntent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceIntentAdapter() {
		if (serviceIntentItemProvider == null) {
			serviceIntentItemProvider = new ServiceIntentItemProvider(this);
		}

		return serviceIntentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IntentDSL.NamedInstance} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NamedInstanceItemProvider namedInstanceItemProvider;

	/**
	 * This creates an adapter for a {@link IntentDSL.NamedInstance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNamedInstanceAdapter() {
		if (namedInstanceItemProvider == null) {
			namedInstanceItemProvider = new NamedInstanceItemProvider(this);
		}

		return namedInstanceItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (intentModelItemProvider != null) intentModelItemProvider.dispose();
		if (extraDataItemProvider != null) extraDataItemProvider.dispose();
		if (implicitIntentItemProvider != null) implicitIntentItemProvider.dispose();
		if (broadCastIntentItemProvider != null) broadCastIntentItemProvider.dispose();
		if (explicitIntentItemProvider != null) explicitIntentItemProvider.dispose();
		if (serviceIntentItemProvider != null) serviceIntentItemProvider.dispose();
		if (namedInstanceItemProvider != null) namedInstanceItemProvider.dispose();
	}

}
